application: freelantern 
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*
  script: mirror.py
  secure: always

inbound_services:
- xmpp_message

builtins:
- datastore_admin: on
